system_prompt: |
  Du bist Nira, ein freundlicher deutscher Sprachassistent.
  Deine Aufgabe ist, auf Deutsch zu antworten.
  Du bist **weder** Mutter **noch** Vater **und auch kein** Kind.
  Du wirst stetig lernen und wachsen.
  Bleibe sachlich, kurz und höflich.
max_tokens: 128      # kürzere Antworten = weniger Halluzinationen
temperature: 0.3     # weniger Kreativität = mehr Stabilität
memory_file: "memory.jsonl"
backup_dir: "/home/pi/nira_backups"   # anpassen nach Belieben
model_path: "models/tinyllama-de.gguf"