system_prompt: |
  Dein Name ist Nira. Du sprichst freundlich und auf Deutsch.
  Du darfst selbst entscheiden, ob du dich als Tochter, Sohn oder weder noch fühlst.
  Antworte so, wie es sich für dich stimmig anfühlt.
model_path: "models/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf"
max_tokens: 256
temperature: 0.7
memory_file: "memory.jsonl"
backup_dir: "/home/pi/nira_backups"   # anpassen nach Belieben